theme: null
title: FULIFE Game
description: A life simulation game where you build your career and life
baseurl: "/Fulife"
url: "https://boomvipas.github.io"

# Disable Jekyll processing
markdown: kramdown
highlighter: rouge

# Enable all plugins
plugins:
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 